### PR TITLE
Increase maximum bearer token size to avoid truncation

### PR DESCRIPTION
**Pull request by ahmedyarub**

### CODE REVIEW

**Comment by ityuhui** [comment]
Thank you @ahmedyarub 

Could you please sign the CLA ? or the PR cannot merge.

**Comment by ahmedyarub** [comment]
> Thank you @ahmedyarub
> 
> Could you please sign the CLA ? or the PR cannot merge.

I tried many times already but I'm not receiving the email!!

**Comment by ahmedyarub** [comment]
Signed

**Comment by ityuhui** [comment]
I think this PR can merge. @brendandburns

**Comment by brendandburns** [comment]
/lgtm
/approve

@ityuhui I believe that you can apply /approve also if you want.

**Comment by ahmedyarub** [comment]
why was this closed without merging?

**Comment by ahmedyarub** [comment]
@brendanburns is there a reason for closing this PR?

**Comment by ityuhui** [comment]
Hi @ahmedyarub 

Don't worry.
Maybe @brendandburns mistakes this PR as an issue and close it.

**Comment by brendanburns** [comment]
Oops I'm sorry I definitely didn't mean to close this. Apologies!

**Comment by ahmedyarub** [comment]
it's OK glad we sorted this out. I'll work on the other PR's today

**Pull request merged**
