### PR TITLE
Use int* as int or bool type function parameters

### PR DESCRIPTION
**Pull request by ityuhui**
fixes:  https://github.com/kubernetes-client/c/issues/209

- Regenerate the client after https://github.com/OpenAPITools/openapi-generator/pull/17179 is merged
- Update examples and readme after the data types of function prameters changes from `int` to `int*`

### CODE REVIEW

**Comment by ityuhui** [comment]
Ping @brendandburns in case this PR is ignored…

**Comment by brendandburns** [comment]
/lgtm
/approve

Apologies for the delay, it's the winter holidays around here so responses are likely to be delayed.

**Comment by ityuhui** [comment]
Happy Holidays ! Thank you for your guidance and help this year.

**Pull request merged**
