### PR TITLE
Support multi-thread

### LINKED ISSUE #34: Considering multi-thread environment
curl_global_cleanup() and curl_global_init() can crash the CURL handle of other threads when making a API request from multi-thread respectively.
In the multi-thread environment, you need to do curl_easy_cleanup() instead of curl_global_cleanup(), and curl_global_init() also should be done only the first time.
curl_easy_init() will also execute if curl_global_init() was not done, so curl_global_init() seems not to have to be done. 
please consider about it.

### PR DESCRIPTION
**Pull request by ityuhui**
The draft to fix #34 

We can talk about the implementation here. 
And some code changes will commit to openapi-generator project and merge back.

### CODE REVIEW

**Comment by brendandburns** [comment]
This implementation looks fine to me. What are the open questions?

**Comment by ityuhui** [comment]
Hi @brendandburns 

No more question except the code review.
I will create the PR for apiClient.{h,c} in openapi-generator as you have agreed the code change.

**Comment by brendandburns** [comment]
This looks good to me.

**Comment by ityuhui** [comment]
Update the code change after https://github.com/kubernetes-client/c/pull/37 is merged.

**Comment by ityuhui** [comment]
Because @brendandburns has approved all the code changes before. I force to merge this pull request now.

**Comment by brendandburns** [comment]
/lgtm
/approve

We may want to add a section documenting how to do multi-threaded programming with the client.

**Comment by ityuhui** [comment]
> 
> We may want to add a section documenting how to do multi-threaded programming with the client.

Yes. I plan to address it:
1. Add a section in README.md
2. Add an example

**Pull request merged**
