### PR TITLE
Bump forward to Kubernetes v1.22.1

### PR DESCRIPTION
**Pull request by ityuhui**
- Bump forward to Kubernetes v1.22.1
- Update examples because the API changes.

### CODE REVIEW

**Comment by brendandburns** [comment]
@ityuhui can you split this into two commits:

* Generated code
* Any fixes needed for the new API

**Comment by ityuhui** [comment]
Sure. I will do it.

**Comment by ityuhui** [comment]
> @ityuhui can you split this into two commits:
> 
> * Generated code
> * Any fixes needed for the new API

Done.

**Pull request merged**
