### PR TITLE
Support specify CURL paths

### PR DESCRIPTION
**Pull request by katepangLiu**
In some cases, we need to specify `CURL_INCLUDE_DIR` and `CURL_LIBRARIES` manually.
```
cmake -DCURL_INCLUDE_DIR=<include> -DCURL_LIBRARIES=<libs> .. 
```

### CODE REVIEW

**Comment by ityuhui** [comment]
Thanks for submitting the PR! 

I'm OK with this change.

But this file is actually generated from https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/C-libcurl/CMakeLists.txt.mustache
Can you please submit this change to that repo first ?

**Comment by ityuhui** [comment]
Hi @brendandburns 

This PR shouldn't be merged here manually.
The author should submit this PR to openapi-generator first.

@katepangLiu 
You should submit the chanage to openapi-generator, or this file will be overwritten by the next auto-generation.

**Comment by katepangLiu** [comment]
> @katepangLiu You should submit the chanage to openapi-generator, or this file will be overwritten by the next auto-generation.

@ityuhui  Ok, I will do that soon.

**Pull request merged**
