### PR TITLE
improve generic list and namespacedlist

### PR DESCRIPTION
**Pull request by DanyT**
- allow empty apiGroup
- select rest api path based on apiGroup value

### CODE REVIEW

**Comment by DanyT** [comment]
a usage like the one bellow will not select the correct rest api path
`
genericClient = genericClient_create(apiClient, "", "v1", "pods");
char *list = Generic_listNamespaced(genericClient, "default");
`

a usage like the one below will result in segfault as strdup need non null input
`
genericClient = genericClient_create(apiClient, NULL, "v1", "pods");
char *list = Generic_listNamespaced(genericClient, "default");
`

**Comment by ityuhui** [comment]
Thank you for fixing this issue !

Do you want to solve the second problem you pointed out?

>   _a usage like the one below will result in segfault as strdup need non null input_

I think the following might be a fix:

```c
genericClient_t* genericClient_create(apiClient_t *client, const char *apiGroup, const char* apiVersion, const char* resourcePlural) {
     ...
     result->apiGroup = apiGroup ? strdup(apiGroup) : NULL;
     ...
}

void genericClient_free(genericClient_t* client) {
    if (client->apiGroup) {
        free(client->apiGroup);
    }
    ...
}
```

**Comment by DanyT** [comment]
yep. will do another pr soon.

**Pull request merged**
