### PR TITLE
Automatically detect shared/static versions of libwebsockets

### PR DESCRIPTION
**Pull request by ahmedyarub**

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks fine to me, but we need you to sign the CLA.

Thanks!

**Comment by ahmedyarub** [comment]
I did sign it multipole times already. Is there anything else I should do?

**Comment by brendandburns** [comment]
@ahmedyarub looks like you may need to sign the EasyCLA too, apologies, looks like there is a migration in progress:

https://github.com/kubernetes/org/issues/2778

**Comment by ahmedyarub** [comment]
> @ahmedyarub looks like you may need to sign the EasyCLA too, apologies, looks like there is a migration in progress:
> 
> [kubernetes/org#2778](https://github.com/kubernetes/org/issues/2778)

I did sign it at least 3 times in the past hours.

**Comment by mrbobbytables** [comment]
If you did sign it, please add to the issues in this thread: https://github.com/kubernetes/org/issues/3068
We're directing the LF to that issue to keep track of the various issues people are encountering

EasyCLA blocking items in this org has been addressed in this PR: https://github.com/kubernetes/test-infra/pull/24381
Should hopefully deploy soonish. Sorry about that =/ Thought it was turned off for all orgs.

**Pull request merged**
