### PR TITLE
Merge 2 useful PRs and other changes from OpenAPITools/openapi-generator repo

### PR DESCRIPTION
**Pull request by ityuhui**
To implement the configuration for kubernetes-client/c,  merge 2 PRs from OpenAPITools/openapi-generator repo:

1. Support SSL client authentication for the c client (#5719)
https://github.com/OpenAPITools/openapi-generator/pull/5719

2. Fix base64 decode funtion (#5642)
https://github.com/OpenAPITools/openapi-generator/pull/5642

/cc @brendandburns

### CODE REVIEW

**Comment by brendandburns** [comment]
This change looks good to me. 

Is this a manual patch? Or did you re-run code generation?

**Comment by ityuhui** [comment]
Hi @brendandburns 

Yes, this is a manual patch.

We do not need re-run code generation because there is no difference between manual patch and code generation for the files ```apiClient.h``` and ```apiClient.c```.

For others model or api files generated by openapi-generator, there is also no important changes. 

But I can re-run code generation too, it does not need big effort.  which solution do you prefer ?

**Comment by brendandburns** [comment]
I'd prefer that we re-run the code generation, I think it is a good practice to never hand-edit the generated files.

Thanks!

**Comment by ityuhui** [comment]
Sure. I will do it.

And ```c/kubernetes/README.md``` which is updated in the PR https://github.com/kubernetes-client/c/pull/5 will not be changed when re-generating.

**Comment by ityuhui** [comment]
Hi @brendandburns

The code generation is re-run and new code change is pushed here. 
Could you please review the latest change change ?

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
