### PR TITLE
Change some parameters of the functions from "char *" to "const char *" to eliminate compilation warnings

### PR DESCRIPTION
**Pull request by minerba**
To fix the issue described in #61 

Change some parameters of the functions from "char *" to "const char *" to eliminate compilation warnings

### CODE REVIEW

**Comment by brendandburns** [comment]
@minerba thanks for the PR, but this code is auto-generated.

If you want to make this change, you need to submit a PR against this file:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache

and then we can re-generate the client.

**Comment by minerba** [comment]
@brendanburns 
Well.. Ok, I understand your comment. 
Can't we edit the file directly without modifying the generator? 
If So. I will submit new PR.

**Comment by brendandburns** [comment]
The problem with manually editing the file is that when we re-generate the client (eg. when there is a new Kubernetes release) then the manual changes will get overwritten.

The Kubernetes API surface is large enough and changes frequently enough that automated generation is the only feasible way to ensure that the client library is comprehensive.

So the only way to make this change is to make it in the generator.

Thanks!

**Review by minerba — COMMENTED** [review]
change openshift

**Pull request closed without merging**
